Frontend -> API: "API Requests (/api/*)"
Frontend -> API: "gRPC Requests (/grpc/*)"

API: {
    label: "API Layer"

    WebServer -> Interfaces: "Interfaces (HTTP, gRPC, Storage)"
    Interfaces -> UseCases: "Use Cases (Business Logic)"
    UseCases -> Storage: "Storage Layer (Repository Implementations)"
    Storage -> DataSource: File System (JSON)"

    WebServer <- Interfaces: "Return Response"
}

API -> Frontend: "Response (JSON / gRPC Response)"

