openapi: 3.0.3
info:
  title: ioaiaaii.net API
  description: This is the API for managing profile-related content such as resumes, releases, live performances, and website projects.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Development Server

paths:
  /api/info:
    get:
      summary: Get Resume Information
      description: Retrieve the profile resume data.
      responses:
        '200':
          description: Resume data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resume'
        '500':
          description: Internal Server Error

  /api/releases:
    get:
      summary: Get Releases
      description: Retrieve all music releases.
      responses:
        '200':
          description: Releases retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Release'
        '500':
          description: Internal Server Error

  /api/live:
    get:
      summary: Get Live Performances
      description: Retrieve all live performances.
      responses:
        '200':
          description: Live performances retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LivePerformance'
        '500':
          description: Internal Server Error

  /api/projects:
    get:
      summary: Get Website Projects
      description: Retrieve all website-related projects.
      responses:
        '200':
          description: Website projects retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WebsiteProject'
        '500':
          description: Internal Server Error

components:
  schemas:
    Resume:
      type: object
      properties:
        name:
          type: string
        title:
          type: string
        email:
          type: string
        linkedIn:
          type: string
        gitHub:
          type: string
        profile:
          type: string
        artistBio:
          type: string
        engineerBio:
          type: string
        experience:
          type: array
          items:
            $ref: '#/components/schemas/ExperienceEntry'
        education:
          type: array
          items:
            $ref: '#/components/schemas/EducationEntry'
        projects:
          type: array
          items:
            $ref: '#/components/schemas/ProjectEntry'
        skillGroups:
          type: array
          items:
            $ref: '#/components/schemas/SkillCategory'
        references:
          type: array
          items:
            type: string

    Release:
      type: object
      properties:
        title:
          type: string
        artist:
          type: string
        releaseDate:
          type: string
        label:
          type: string
        discogsLink:
          type: string
        bandcampLink:
          type: string
        soundCloudLink:
          type: string
        description:
          type: string

    LivePerformance:
      type: object
      properties:
        title:
          type: string
        date:
          type: string
        eventLink:
          type: string
        listenLink:
          type: string

    WebsiteProject:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        link:
          type: string

    ExperienceEntry:
      type: object
      properties:
        role:
          type: string
        company:
          type: string
        location:
          type: string
        startDate:
          type: string
        endDate:
          type: string
        description:
          type: array
          items:
            type: string

    EducationEntry:
      type: object
      properties:
        degree:
          type: string
        institution:
          type: string
        location:
          type: string
        specialization:
          type: string
        dissertation:
          type: string

    ProjectEntry:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        link:
          type: string

    SkillCategory:
      type: object
      properties:
        category:
          type: string
        skills:
          type: array
          items:
            type: string
