openapi: 3.0.0
info:
  title: ioaiaaii.net API
  description: API for managing content including resumes, releases, live performances, and projects.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local Development Server

paths:
  /api/info:
    get:
      summary: Get resume information
      description: Returns resume data including personal information, experience, and education.
      responses:
        '200':
          description: A JSON object representing the resume.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resume'
        '500':
          description: Internal server error.

  /api/releases:
    get:
      summary: Get releases
      description: Returns a list of releases (e.g., albums or content created by the artist).
      responses:
        '200':
          description: A list of releases in JSON format.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Release'
        '500':
          description: Internal server error.

  /api/live:
    get:
      summary: Get live performances
      description: Returns a list of live performances.
      responses:
        '200':
          description: A list of live performances in JSON format.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LivePerformance'
        '500':
          description: Internal server error.

  /api/projects:
    get:
      summary: Get projects
      description: Returns a list of engineering or other website projects.
      responses:
        '200':
          description: A list of projects in JSON format.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/WebsiteProjectEntry'
        '500':
          description: Internal server error.

components:
  schemas:
    Resume:
      type: object
      properties:
        name:
          type: string
          description: Full name of the individual.
        title:
          type: string
          description: Professional title.
        email:
          type: string
          description: Contact email address.
        linkedIn:
          type: string
          description: LinkedIn profile URL.
        gitHub:
          type: string
          description: GitHub profile URL.
        profile:
          type: string
          description: Short personal or professional profile.
        artistBio:
          type: string
          description: Biography for the artist.
        engineerBio:
          type: string
          description: Biography for the engineer role.
        experience:
          type: array
          items:
            $ref: '#/components/schemas/ExperienceEntry'
        education:
          type: array
          items:
            $ref: '#/components/schemas/EducationEntry'
        projects:
          type: array
          items:
            $ref: '#/components/schemas/ProjectEntry'
        skillGroups:
          type: array
          items:
            $ref: '#/components/schemas/SkillCategory'
        references:
          type: array
          items:
            type: string

    Release:
      type: object
      properties:
        title:
          type: string
        artist:
          type: string
        releaseDate:
          type: string
          format: date
        label:
          type: string
        discogsLink:
          type: string
        bandcampLink:
          type: string
        soundCloudLink:
          type: string
        description:
          type: string

    LivePerformance:
      type: object
      properties:
        title:
          type: string
        date:
          type: string
          format: date
        eventLink:
          type: string
          nullable: true
        listenLink:
          type: string
          nullable: true

    WebsiteProjectEntry:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        link:
          type: string
        category:
          type: string

    ExperienceEntry:
      type: object
      properties:
        role:
          type: string
        company:
          type: string
        location:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        description:
          type: array
          items:
            type: string

    EducationEntry:
      type: object
      properties:
        degree:
          type: string
        institution:
          type: string
        location:
          type: string
        specialization:
          type: string
          nullable: true
        dissertation:
          type: string
          nullable: true
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date

    ProjectEntry:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        link:
          type: string

    SkillCategory:
      type: object
      properties:
        category:
          type: string
        skills:
          type: array
          items:
            type: string
