run:
  timeout: 5m
  concurrency: 4

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - goconst        # Finds repeated strings that could be turned into constants
    - gocyclo        # Reports functions with high cyclomatic complexity
    - gofmt          # Checks that your code is properly formatted
    - goimports      # Checks that imports are properly organized
    - dupl           # Finds code that has been duplicated
    - misspell       # Detects commonly misspelled English words
    - unconvert      # Finds unnecessary type conversions
    - gosec          # Runs security checks
